# Generated by Django 4.2.3 on 2023-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='wrgfdsv', upload_to='pics'),
            preserve_default=False,
        ),
    ]
